=== Ksenyia/JavaTask04/SimpleWebApp02/src/main/resources/orangery.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/flowers"
        xmlns:tns="http://www.example.com/flowers"
        elementFormDefault="qualified">

    <element name="flowers">
        <complexType>
            <sequence>
                <element ref="tns:flower" minOccurs="16" maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>

    <complexType name="Flower">
    <sequence>
        <element name="name" type="string" />
        <element name="origin" type="string" />
        <element name="soil" type="tns:Soil" />
        <element name="visual-parameters" type="tns:Visual" />
        <element name="growing-tips" type="tns:Growing" />
    </sequence>
    <attribute name="id" use="required">
        <simpleType>
            <restriction base="ID">
                <pattern value="([a-z])[0-9]{1,3}" />
            </restriction>
        </simpleType>
    </attribute>
    <attribute name="multiplying" use="optional" default="seeds">
        <simpleType>
            <restriction base="string">
                <enumeration value="cuttings"></enumeration>
                <enumeration value="leaves"></enumeration>
                <enumeration value="seeds"></enumeration>
            </restriction>
        </simpleType>
    </attribute>
    </complexType>

    <complexType name="Biennial">
        <complexContent>
            <extension base="tns:Flower">
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Perennials">
        <complexContent>
            <extension base="tns:Flower">
            </extension>
        </complexContent>
    </complexType>
    
        <complexType name="Annual">
        <complexContent>
            <extension base="tns:Flower">
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Visual">
        <sequence>
            <element name="stem-color" type="string" />
            <element name="leaf-color" type="string" />
            <element name="plant-size" type="integer" />
        </sequence>
    </complexType>

    <complexType name="Growing">
        <sequence>
            <element name="temperature" type="tns:Temperature" />
            <element name="watering" type="integer" />
        </sequence>
    </complexType>

        <simpleType name="Soil">
        <restriction base="string">
            <enumeration value="podzolic"></enumeration>
            <enumeration value="subsoil"></enumeration>
            <enumeration value="sod-podzolic"></enumeration>
        </restriction>
    </simpleType>

    <simpleType name="Temperature">
        <restriction base="integer">
            <minInclusive value="-50"></minInclusive>
            <maxInclusive value="60"></maxInclusive>
        </restriction>
    </simpleType>
    <element name="flower" type="tns:Flower" abstract="true" />
    <element name="perennials-flower" type="tns:Perennials" substitutionGroup="tns:flower" />
    <element name="biennial-flower" type="tns:Biennial" substitutionGroup="tns:flower" />
    <element name="annual-flower" type="tns:Annual" substitutionGroup="tns:flower" />

</schema>

=== Ksenyia/JavaTask04/SimpleWebApp02/src/main/resources/orangery.xml
<?xml version="1.0" encoding="UTF-8"?>
<flowers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.com/flowers"
         xsi:schemaLocation="http://www.example.com/flowers orangery.xsd">
  
    <perennials-flower id="f1" multiplying="cuttings">
        <name>Peony</name>
        <origin>Greece</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>75</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <watering>80</watering>
        </growing-tips>
    </perennials-flower>
    <perennials-flower id="f2" multiplying="cuttings">
        <name>Rose</name>
        <origin>Greece</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>75</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <watering>80</watering>
        </growing-tips>
    </perennials-flower>    
    <biennial-flower id="f3" multiplying="seeds">
        <name>Forget-me-not</name>
        <origin>Holland</origin>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Green</leaf-color>
            <plant-size>10</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <watering>80</watering>
        </growing-tips>
    </biennial-flower>

    
    <biennial-flower id="f4" multiplying="seeds">
        <name>Foxglove</name>
        <origin>Holland</origin>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Green</leaf-color>
            <plant-size>60</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>20</temperature>
            <watering>80</watering>
        </growing-tips>
    </biennial-flower>
    
    
    <biennial-flower id="f5" multiplying="seeds">
        <name>Stock</name>
        <origin>Asia</origin>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Violet</leaf-color>
            <plant-size>30</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>22</temperature>
            <watering>60</watering>
        </growing-tips>
    </biennial-flower>

    <perennials-flower id="f6" multiplying="seeds">
        <name>Kermek</name>
        <origin>Central Asia</origin>
        <soil>subsoil</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Blue</leaf-color>
            <plant-size>40</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>18</temperature>
            <watering>10</watering>
        </growing-tips>
    </perennials-flower>

    <perennials-flower id="f7" multiplying="seeds">
        <name>Abelia</name>
        <origin>Japan</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Pink</leaf-color>
            <plant-size>150</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>16</temperature>
            <watering>70</watering>
        </growing-tips>
    </perennials-flower>

    <annual-flower id="f8" multiplying="cuttings">
        <name>Impatiens</name>
        <origin>Africa</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Pink</leaf-color>
            <plant-size>30</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>21</temperature>
            <watering>170</watering>
        </growing-tips>
    </annual-flower>

    <annual-flower id="f9" multiplying="seeds">
        <name>Vallota</name>
        <origin>South Africa</origin>
        <soil>podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Red</leaf-color>
            <plant-size>60</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>25</temperature>
            <watering>90</watering>
        </growing-tips>
    </annual-flower>

    <perennials-flower id="f10" multiplying="leaves">
        <name>Hedychium</name>
        <origin>South Asia</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Yellow</leaf-color>
            <plant-size>45</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>27</temperature>
            <watering>105</watering>
        </growing-tips>
    </perennials-flower>

    <perennials-flower id="f11" multiplying="cuttings">
        <name>Jasminum</name>
        <origin>China</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>190</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
        </growing-tips>
    </perennials-flower>

    <perennials-flower id="f12" multiplying="seeds">
        <name>Iris</name>
        <origin>Holland</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>40</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
        </growing-tips>
    </perennials-flower>

    <perennials-flower id="f13" multiplying="seeds">
        <name>Gerbera</name>
        <origin>Holland</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Red</leaf-color>
            <plant-size>60</plant-size>
         </visual-parameters>
         <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
         </growing-tips>
    </perennials-flower>

    <perennials-flower id="f14" multiplying="seeds">
        <name>Tulip</name>
        <origin>Iran</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Yellow</leaf-color>
            <plant-size>30</plant-size>
        </visual-parameters>
         <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
        </growing-tips>
    </perennials-flower>

    <annual-flower id="f15" multiplying="cuttings">
        <name>Chrysanthemum</name>
        <origin>Asia</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>55</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
        </growing-tips>
    </annual-flower>

    <biennial-flower id="f16" multiplying="cuttings">
        <name>Lily</name>
        <origin>Greece</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>White</leaf-color>
            <plant-size>90</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
        </growing-tips>
    </biennial-flower>

    <annual-flower id="f17" multiplying="cuttings">
        <name>Clove</name>
        <origin>Germany</origin>
        <soil>sod-podzolic</soil>
        <visual-parameters>
            <stem-color>Green</stem-color>
            <leaf-color>Red</leaf-color>
            <plant-size>70</plant-size>
        </visual-parameters>
        <growing-tips>
            <temperature>19</temperature>
            <watering>85</watering>
        </growing-tips>
    </annual-flower>
</flowers>
